  - name: configure yum repos
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
  - name: configure yum repos for rabbitmq
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
  - name: Install RabbitMQ
    ansible.builtin.package:
      name: rabbitmq-server
      state: present
  - name: Enable and start rabbitmq-server 
    ansible.builtin.service:
      name: rabbitmq-server 
      state: started
      enabled: true
  - name: change user name and password
    ansible.builtin.command: rabbitmqctl add_user {{rbmq_user}} {{rbmq_password}}
  - name: set permissions
    ansible.builtin.shell: rabbitmqctl set_permissions -p / {{rbmq_user}} ".*" ".*" ".*"