- name: add user roboshop
  ansible.builtin.user:
    name: roboshop
- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: Download application
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp
- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes